# Generated by Django 4.0.6 on 2022-07-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_tag_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured_img',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_img',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
