# Generated by Django 4.0.6 on 2022-07-30 15:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_buckethistory_owner_and_more'),
        ('goods', '0003_category_featured_img_alter_product_featured_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('count', models.SmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.product')),
            ],
        ),
    ]
