# Generated by Django 4.0.6 on 2022-08-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'В обробці'), ('SENT', 'Відправлено'), ('TAKEN', 'Отримано')], default='PROCESSING', max_length=50),
        ),
    ]
