# Generated by Django 4.0.6 on 2022-08-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_orderproduct_client_alter_orderproduct_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_name',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
