# Generated by Django 4.0.6 on 2022-08-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_alter_ordercard_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercard',
            name='total',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'В обробці'), ('DONE', 'Готово')], default='PROCESSING', max_length=50),
        ),
    ]
