# Generated by Django 4.1.3 on 2022-11-20 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_ordercard_total_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercard',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='session_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.ordercard'),
        ),
        migrations.AlterField(
            model_name='ordercard',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'В обробці'), ('PREPARING', 'Готується до відправки'), ('SENT', 'Відправлено'), ('TAKEN', 'Отримано')], default='PROCESSING', max_length=25),
        ),
    ]
