# Generated by Django 4.1.3 on 2022-12-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_alter_orderproduct_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercard',
            name='payment_way',
            field=models.CharField(choices=[('ON_MAIL', 'Накладений платіж'), ('CARD', 'Оплата на картку')], default='Оберіть вид оплати', max_length=25),
        ),
        migrations.AlterField(
            model_name='ordercard',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'В обробці'), ('PREPARING', 'Готується до відправки'), ('SENT', 'Відправлено'), ('TAKEN', 'Отримано')], default='В обробці', max_length=25),
        ),
    ]
