# Generated by Django 4.1.3 on 2023-02-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_ordercard_payment_way_alter_ordercard_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created']},
        ),
    ]
