# Generated by Django 4.1.3 on 2023-02-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created']},
        ),
    ]
