# Generated by Django 4.0.6 on 2022-07-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buckethistory',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='buckethistory',
            name='product_bought',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Bucket',
        ),
        migrations.DeleteModel(
            name='BucketHistory',
        ),
    ]
